Fix breakage in ctest.py.
Spotted the following error on the bots:

Traceback (most recent call last):
  File "bin/ctest", line 318, in <module>
    main()
  File "bin/ctest", line 314, in main
    options.remote, not options.cache)
TypeError: RunAUTestHarness() takes exactly 9 arguments (8 given)

http://chromeos-botmaster.mtv.corp.google.com:8026/builders/x86%20AGZ%20Full/builds/545/steps/cbuild/logs/stdio ( http://bit.ly/fdwOq1 )

This change fixes the error introduced in b54301bb9a284302d0f82c12a8753c3302a86d88.

TEST=Verify that new argument is passed through.
BUG=chromium-os:12211

Change-Id: Ibe8ee2f1fd0001525a5699a9dc107730f9c181de

Review URL: http://codereview.chromium.org/6625035